export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  WORKER = 'WORKER',
  ADMIN = 'ADMIN',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum BookingStatus {
  REQUESTED = 'REQUESTED',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  WORKER_ON_THE_WAY = 'WORKER_ON_THE_WAY',
  ARRIVED = 'ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PAYMENT_RELEASED = 'PAYMENT_RELEASED',
  RATED = 'RATED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  UPI = 'UPI',
  CASH = 'CASH',
  NET_BANKING = 'NET_BANKING',
  CARD = 'CARD',
}

export enum ComplaintCategory {
  WORKER_BEHAVIOR = 'WORKER_BEHAVIOR',
  SERVICE_QUALITY = 'SERVICE_QUALITY',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  LATE_ARRIVAL = 'LATE_ARRIVAL',
  WRONG_PRICING = 'WRONG_PRICING',
  BILLING = 'BILLING',
  BEHAVIOR = 'BEHAVIOR',
  DELAY = 'DELAY',
  SAFETY = 'SAFETY',
  OTHER = 'OTHER',
}

export enum ComplaintStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum DocumentType {
  AADHAAR = 'AADHAAR',
  PAN = 'PAN',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  POLICE_VERIFICATION = 'POLICE_VERIFICATION',
  SKILL_CERTIFICATE = 'SKILL_CERTIFICATE',
  COOPERATIVE_MEMBERSHIP = 'COOPERATIVE_MEMBERSHIP',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  PHOTO_ID = 'PHOTO_ID',
  OTHER = 'OTHER',
}
